apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: 381492301125.dkr.ecr.ap-southeast-1.amazonaws.com/guestbook:latest
        volumeMounts:
          - name: aws-credentials-vl
            mountPath: /root/.aws/credentials
            subPath: credentials
            readOnly: true
        ports:
        - name: http-server
          containerPort: 3000
      volumes:
      - name: aws-credentials-vl
        secret:
          secretName: aws-secret
      imagePullSecrets:
        - name: ecr-secret