apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1  # Still using a single replica, just like in the original ReplicationController
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis:latest  # You can specify a version like redis:6.2.6-alpine if you prefer
        ports:
        - name: redis-server
          containerPort: 6379
